### ISSUE TITLE
Merge `binaryberry/seal` master into this repo

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/seal#138]
Bring the two in line with each other.

**Comment by issyl0** [comment]
```
git remote add upstream https://github.com/binaryberry/seal
git fetch upstream
git log --oneline master..upstream/master

a9a069b (upstream/master) Merge pull request #303 from i4a/rvm-setup
cbe2d40 :construction_worker: updates travis ruby version
e89e675 :wrench: drop .rvmrc in favour of .ruby-version and .ruby-gemset; relax ruby 2.5 version to allow any patch version
ae97f20 Merge pull request #259 from rgeraldporter/master
6e0d8d9 Merge pull request #298 from alex-mohemian/master
beef6c0 Update Slack::Poster
deface8 Downgrade bundler
deface1 Update gems
108b95f Merge pull request #294 from patrobinson/raise-exception-if-slack-posting-fails
d0706c5 Fix tabs
f85a7bd Raise an exception if Slack posting fails
04086d2 Merge pull request #288 from binaryberry/ruby-upgrade
36afb22 Ruby upgrade to 2.5.1
cec6656 Adds option to filter already-reviewed pull requests, regardless of approval status
```

That's what we're dealing with as of today.

**Comment by ChrisBAshton** [comment]
Hmmm there are a lot of conflicts if I try to merge this in. A fair bit of it is unnecessary for us or has already been done by us (Travis ruby version, dropping .rvmrc, ruby upgrade, [renaming `slack_poster` to `slack_lib`](https://github.com/binaryberry/seal/commit/beef6c08c7af79146747bb99f6bd6ecf25cf2d38), etc). The only thing I can see that might be worth carrying over is "[Raise an exception if Slack posting fails](https://github.com/binaryberry/seal/commit/f85a7bd95dee4e369b7c1624a4f1535364be1c6b)", and "[Adds option to filter already-reviewed pull requests, regardless of approval status](https://github.com/binaryberry/seal/commit/cec6656d73f13017b9e2fcddaec227b85c224c06)".

I think we can add these features ourselves manually if we really want them. In the meantime, I reckon we should action #139 👍
