### ISSUE TITLE
Can we have the seal at 8am please?

### ISSUE THREAD

**Issue by benvand** [alphagov/seal#86]
I'm finding the seal _super_ useful over on Marketplace. 🙌 
The only problem is that I usually get in at around 8am.

Prior to daylight savings the seal Slack message was coming through at 8:31, which was OK for me. It's now coming through at 9:31.

Is there any chance we can move the morning time to 8am? 🙏 🙏 🙏

**Comment by issyl0** [comment]
Is this still a problem? Now we've flipped back to UTC it'll be at the earlier time. Timezones are hard.
